version: '3.7'
services:
  aws:
    image: 'localstack/localstack:1.2.0'
    container_name: 'localstack'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=127.0.0.1
    ports:
      - '4566:4566'