server:
  port: 8080

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: "error"
        util:
          EC2MetadataUtils: "error"
spring:
  application:
    name: "PocSQS"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://localhost:4566/000000000000/sample-queue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeout: 10000
    numberOfThreads: 1
